// GENERATED by scripts/publish.mjs. Build b16665df2340.
const CACHE = 'reflect-b16665df2340';
const SHELL = ['./', './index.html', './manifest.webmanifest', './icon-192.png', './icon-512.png'];
// The browser always fetches this file itself fresh, ignoring its own cache, which is why the
// CACHE name above is always current. c.addAll(SHELL) does not get the same treatment: it is a
// plain fetch by URL, which the CDN in front of GitHub Pages can still answer from an edge copy
// that has not caught up yet, even seconds after a deploy. That mismatch is exactly how a cache
// whose name says the latest build ended up holding an older page inside it. Busting the query
// on this one fetch, then storing the result under the plain URL so the app's own fetch handler
// still finds it, forces every install to grab what is actually live right now.
self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => Promise.all(SHELL.map(async url => {
    const bust = url + (url.includes('?') ? '&' : '?') + 'v=' + CACHE;
    const res = await fetch(bust, { cache: 'reload' });
    if (res.ok) await c.put(url, res);
  }))).then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', e => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET' || url.origin !== self.location.origin) return;   // never touch the API or anything private
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then(hit => {
    // Falls back to hit on a failed fetch, same as before, but hit itself is undefined for
    // anything outside the small SHELL list requested for the first time: respondWith(undefined)
    // is a hard network-error response, not an ordinary failed fetch, the one case this could
    // still produce. A synthesised response only when there is genuinely nothing else to offer.
    const live = fetch(e.request).then(res => { if (res.ok) caches.open(CACHE).then(c => c.put(e.request, res.clone())); return res; })
      .catch(() => hit ?? new Response('Offline', { status: 503, statusText: 'Offline' }));
    return hit || live;
  }));
});

// The evening reminder and the morning reflection. The body is written by the nudge function.
self.addEventListener('push', e => {
  let d = { title: 'Reflect', body: '', url: './' };
  try { d = { ...d, ...e.data.json() }; } catch (_) { d.body = e.data ? e.data.text() : ''; }
  e.waitUntil(self.registration.showNotification(d.title, {
    body: d.body,
    tag: d.url,                 // a second nudge about the same thing replaces the first
    icon: './icon-192.png',
    badge: './icon-192.png',
    data: { url: d.url },
  }));
});

// Focus the window if it is already open rather than stacking up new ones.
self.addEventListener('notificationclick', e => {
  e.notification.close();
  // Resolved against the SW's own registration scope (the app's real base path), not
  // self.location.href (sw.js's own URL). Reflect is hosted on a GitHub Pages PROJECT page
  // (https://.../reflect-app/), not a user root site, so a root-absolute url like '/#tonight'
  // resolves to the bare domain root either way, stripping /reflect-app/ entirely and sending
  // every tap to a page that is not this app at all. The url the nudge and monthly-review
  // functions send is a bare relative fragment (see notify.ts) specifically so this resolves
  // correctly under whatever base path the app is actually deployed at.
  const target = new URL(e.notification.data && e.notification.data.url || './', self.registration.scope).href;
  e.waitUntil(self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then(list => {
    for (const c of list) if (c.url.startsWith(self.location.origin) && 'focus' in c) { c.navigate(target); return c.focus(); }
    return self.clients.openWindow(target);
  }));
});
