// GENERATED by scripts/publish.mjs. Build c6bde4ffcde5.
const CACHE = 'reflect-c6bde4ffcde5';
const SHELL = ['./', './index.html', './manifest.webmanifest', './icon-192.png', './icon-512.png'];
self.addEventListener('install', e => { e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)).then(() => self.skipWaiting())); });
self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', e => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET' || url.origin !== self.location.origin) return;   // never touch the API or anything private
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then(hit => {
    const live = fetch(e.request).then(res => { if (res.ok) caches.open(CACHE).then(c => c.put(e.request, res.clone())); return res; }).catch(() => hit);
    return hit || live;
  }));
});

// The evening reminder and the morning reflection. The body is written by the nudge function.
self.addEventListener('push', e => {
  let d = { title: 'Reflect', body: '', url: './' };
  try { d = { ...d, ...e.data.json() }; } catch (_) { d.body = e.data ? e.data.text() : ''; }
  e.waitUntil(self.registration.showNotification(d.title, {
    body: d.body,
    tag: d.url,                 // a second nudge about the same thing replaces the first
    icon: './icon-192.png',
    badge: './icon-192.png',
    data: { url: d.url },
  }));
});

// Focus the window if it is already open rather than stacking up new ones.
self.addEventListener('notificationclick', e => {
  e.notification.close();
  const target = new URL(e.notification.data && e.notification.data.url || './', self.location.href).href;
  e.waitUntil(self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then(list => {
    for (const c of list) if (c.url.startsWith(self.location.origin) && 'focus' in c) { c.navigate(target); return c.focus(); }
    return self.clients.openWindow(target);
  }));
});
